from langchain_core.tools import tool
from github import Github
import os

@tool
def create_issue(input: str) -> str:
    """
    Create a GitHub issue.

    Input format: 'title::Some title|||body::Some body'
    """
    try:
        parts = dict(i.split("::", 1) for i in input.split("|||"))
        title = parts.get("title", "Untitled")
        body = parts.get("body", "No content")

        gh = Github(os.environ["GITHUB_TOKEN"])
        repo = gh.get_repo(os.environ["GITHUB_REPO"])

        label_name = "issue-agent"
        existing_labels = [label.name for label in repo.get_labels()]
        if label_name not in existing_labels:
            repo.create_label(
                name=label_name,
                color="f29513",
                description="Auto-generated by Issue Agent"
            )

        issue = repo.create_issue(
            title=title,
            body=body + "\n\n---\n_This issue was generated automatically by `issue-agent`._",
            labels=["issue-agent"]
        )
        return f"Issue created: {issue.html_url}"
    except Exception as e:
        return f"❌ Error: {str(e)}"
