from github import Github
import os

def run_generator_agent(data):
    print("****************DATA*******************************")
    print(data)
    print("****************DATA*******************************")

    if not data.get("create_issues"):
        print("No new issues needed.")
        return

    issues = data.get("ISSUES", [])
    if not issues:
        print("No issue details found.")
        return

    gh = Github(os.environ["GITHUB_TOKEN"])
    repo = gh.get_repo(os.environ["GITHUB_REPO"])

    if not repo.has_issues:
        print("🚫 Issues are disabled for this repository.")
        return

    label_name = "issue-agent"
    existing_labels = [label.name for label in repo.get_labels()]
    if label_name not in existing_labels:
        repo.create_label(name=label_name, color="f29513", description="Auto-generated by Issue Agent")

    for issue in issues:
        title = issue.get("title")
        body = issue.get("body")
        if title and body:
            full_title = f"[Issue Agent] {title}"
            full_body = f"{body}\n\n---\n_This issue was generated automatically by `issue-agent`._"
            repo.create_issue(title=full_title, body=full_body, labels=['issue-agent'])
            print(f"✅ Created issue: {full_title}")
