name: AI Code Review 

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.1.0
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 85
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      
      - name: Upload code review result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-review-result
          path: code_review_result.json